// app/GameContext.tsx
import React, { createContext, useState, useContext, ReactNode } from 'react';
import { useRouter } from 'expo-router';

const MIN_JUGADORES = 4; 
const MAX_JUGADORES = 12; 
const MIN_IMPOSTORES = 1;

// Lista de palabras/roles para los tripulantes
const KEYWORDS: string[] = [
    "Messi",
    "Maradona",
    "Ricardo Fort",
    "Coscu",
    "Duki",
    "Bizarrap",
    "Wos",
    "Trueno",
    "Khea",
    "Paulo Londra",
    "L-Gante",
    "Tini Stoessel",
    "Moria Casán",
    "Mirta Legrand",
    "Susana Giménez",
    "Tinelli",
    "Guido Kaczka",
    "Alf",
    "Homer",
    "Marge",
    "Bart",
    "Lisa",
    "Maggie",
    "Milhouse",
    "Ned Flanders",
    "Apu",
    "Mr. Burns",
    "Moe",
    "John Wick",
    "Neo",
    "Trinity",
    "Morpheus",
    "Marty McFly",
    "Doc Brown",
    "Biff Tannen",
    "Tony Montana",
    "Scarface",
    "Vito Corleone",
    "Michael Corleone",
    "Fredo Corleone",
    "Sonny Corleone",
    "Joker",
    "Batman",
    "Robin",
    "Alfred",
    "Bane",
    "Superman",
    "Wonder Woman",
    "Flash",
    "Aquaman",
    "Iron Man",
    "Captain America",
    "Hulk",
    "Thor",
    "Black Widow",
    "Spiderman",
    "Venom",
    "Deadpool",
    "Wolverine",
    "Magneto",
    "Professor X",
    "Shrek",
    "Burro",
    "Fiona",
    "Gato con Botas",
    "Buzz Lightyear",
    "Woody",
    "Andy (Toy Story)",
    "Sid",
    "Elsa",
    "Anna",
    "Olaf",
    "Sven",
    "Jack Sparrow",
    "Will Turner",
    "Elizabeth Swann",
    "Davy Jones",
    "Harry Potter",
    "Hermione Granger",
    "Ron Weasley",
    "Albus Dumbledore",
    "Severus Snape",
    "Lord Voldemort",
    "Gandalf",
    "Frodo",
    "Aragorn",
    "Legolas",
    "Gollum",
    "Sam",
    "Bilbo",
    "Thorin",
    "Smaug",
    "Rick Grimes",
    "Daryl",
    "Michonne",
    "Negan",
    "Walter White",
    "Jesse Pinkman",
    "Saul Goodman",
    "Gustavo Fring",
    "Don Cornelio",
    "Ricardo Iorio",
    "Pappo",
    "Charly García",
    "Fito Páez",
    "Spinetta",
    "Andrés Calamaro",
    "Gustavo Cerati",
    "Simba (El Rey León)",
    "Nala (El Rey León)",
    "Mufasa (El Rey León)",
    "Aladdín (Aladdín)",
    "Jazmín (Aladdín)",
    "Genio (Aladdín)",
    "Jafar (Aladdín)",
    "Peter Pan (Peter Pan)",
    "Campanita (Peter Pan)",
    "Capitán Garfio (Peter Pan)",
    "Winnie the Pooh ",
    "Piglet (Winnie the Pooh)",
    "Tigger (Winnie the Pooh)",
    "Eeyore (Winnie the Pooh)",
    "Pinocho (Pinocho)",
    "Geppetto (Pinocho)",
    "Dumbo (Dumbo)",
    "Timothy (Dumbo)",
    "Bambi (Bambi)",
    "Hada Azul (Pinocho)",
    "Aurora (La Bella Durmiente)",
    "Maléfica (La Bella Durmiente)",
    "Felipe (La Bella Durmiente)",
    "Cenicienta (Cenicienta)",
    "Hada Madrina (Cenicienta)",
    "Anastasia (Cenicienta)",
    "Ariel (La Sirenita)",
    "Sebastián (La Sirenita)",
    "Flounder (La Sirenita)",
    "Ursula (La Sirenita)",
    "Tarzán (Tarzán)",
    "Jane (Tarzán)",
    "Clayton (Tarzán)",
    "Tiana (La Princesa y el Sapo)",
    "Naveen (La Princesa y el Sapo)",
    "Doctor Facilier (La Princesa y el Sapo)",
    "Rapunzel (Enredados)",
    "Flynn Rider (Enredados)",
    "Maximus (Enredados)",
    "Gothel (Enredados)",
    "Ralph (Ralph el Demoledor)",
    "Vanellope (Ralph el Demoledor)",
    "Miguel (Coco)",
    "Héctor (Coco)",
    "Mama Coco",
    "Remy (Ratatouille)",
    "Linguini (Ratatouille)",
    "Colette (Ratatouille)",
    "Anton Ego (Ratatouille)",
    "Merida (Valiente)",
    "Rey Fergus (Valiente)",
    "Bolt (Bolt)",
    "Edward Elric (Fullmetal Alchemist)",
    "Alphonse Elric (Fullmetal Alchemist)",
    "Roy Mustang (Fullmetal Alchemist)",
    "Light Yagami (Death Note)",
    "L (Death Note)",
    "Misa Amane (Death Note)",
    "Near (Death Note)",
    "Yagami Soichiro (Death Note)",
    "Tanjiro Kamado (Demon Slayer)",
    "Nezuko Kamado (Demon Slayer)",
    "Zenitsu Agatsuma (Demon Slayer)",
    "Inosuke Hashibira (Demon Slayer)",
    "Gyu Tomioka (Demon Slayer)",
    "Eren Jaeger (Attack on Titan)",
    "Mikasa Ackerman (Attack on Titan)",
    "Armin Arlert (Attack on Titan)",
    "Levi Ackerman (Attack on Titan)",
    "Erwin Smith (Attack on Titan)",
    "Naruto Uzumaki (Naruto)",
    "Hinata Hyuga (Naruto)",
    "Gaara (Naruto)",
    "Jiraiya (Naruto)",
    "Sakura Haruno (Naruto)",
    "Ichigo Kurosaki (Bleach)",
    "Rukia Kuchiki (Bleach)",
    "Orihime Inoue (Bleach)",
    "Byakuya Kuchiki (Bleach)",
    "Kenpachi Zaraki (Bleach)",
    "Luffy (One Piece)",
    "Zoro (One Piece)",
    "Nami (One Piece)",
    "Sanji (One Piece)",
    "Chopper (One Piece)",
    "Robin (One Piece)",
    "Usopp (One Piece)",
    "Brook (One Piece)",
    "Franky (One Piece)",
    "Gon (Hunter x Hunter)",
    "Killua (Hunter x Hunter)",
    "Kurapika (Hunter x Hunter)",
    "ibai (influencer)",
"auronplay (influencer)",
"rubius (influencer)",
"vegetta777 (influencer)",
"willyrex (influencer)",
"german garmendia (influencer)",
"julioprofe (influencer)",
"martin sirio (la faraona)",
"momo (influencer argentino)",
"marito baracus (influencer argentino)",
"flor vigna (influencer)",
"nati jota (influencer)",
"lit killah (cantante/influencer)",
"nicki nicole (cantante/influencer)",
"cazzu (cantante/influencer)",
"tiago pzk (cantante/influencer)",
"ysy a (cantante/influencer)",
"coscu army kid (influencer)",
"manu ginobili (influencer deportivo)",
"pewdiepie (influencer)",
"mrbeast (influencer)",
"kai cenat (influencer)",
"speed (influencer)",
"pokimane (influencer)",
"amouranth (influencer)",
"el rey león",
"aladdín",
"la sirenita",
"la bella y la bestia",
"la bella durmiente",
"blanca nieves y los siete enanos",
"pinocho",
"dumbo",
"bambi",
"cenicienta",
"peter pan",
"winnie the pooh",
"la dama y el vagabundo",
"los aristogatos",
"robin hood",
"taron y el caldero mágico",
"el zorro y el sabueso",
"oliver y su pandilla",
"la princesa y el sapo",
"enredados",
"valiente",
"frozen",
"moana",
"zootopia",
"intensamente",
"coco",
"soul",
"un gran dinosaurio",
"ratatouille",
"cars",
"buscando a nemo",
"monsters inc",
"toy story",
"los increíbles",
"up: una aventura de altura",
"wall-e",
"unidos",
"elementos",
"luca",
"volver al futuro",
"el padrino",
"scarface",
"el caballero de la noche",
"el hombre de acero",
"la liga de la justicia",
"mujer maravilla",
"aquaman",
"linterna verde",
"batman inicia",
"joker",
"escuadrón suicida",
"deadpool",
"logan",
"x-men",
"capitán américa el primer vengador",
"iron man",
"thor",
"guardianes de la galaxia",
"avengers los vengadores",
"doctor strange hechicero supremo",
"black panther",
"spider-man de regreso a casa",
"mi vecino totoro",
"el castillo ambulante",
"el viaje de chihiro",
"la princesa mononoke",
"Hollow Knight",
"Celeste",
"Stardew Valley",
"Undertale",
"Hades",
"Dead Cells",
"Gta San Andreas",
"Gta V",
"The Witcher 3",
"Red Dead Redemption 2",
"Cyberpunk 2077",
"Assassin's Creed",
"Minecraft",
"Fortnite",
"League of Legends",
"Counter Strike",
"Goku",
"Vegeta",
"Piccolo",
"Frieza",
"Cell",
"Majin Buu",
"Naruto",
"Sasuke",
"Sakura",
"Kakashi",
"Jiraiya",
"Ichigo",
"Davo",
"La Cobra",
"CJ",
"Tommy Vercetti",
"Niko Bellic",
"Kratos",
"Atreus",
"Zeus",
"Play 2",
"PES 06",
"Resident Evil 4",
"Silent Hill",
"Metal Gear Solid",
"Final Fantasy VII",
"Macri",
"Gravity Falls",
"Steven Universe",
"Hora de Aventura",
"Un Show Más",
"Regular Show",
"Clarence",
"Los Padrinos Mágicos",
"Bob Esponja",
"Patricio Estrella",
"Calamardo Tentáculos",
"Steam",
"Epic Games",
"Ubisoft",
"EA Games",
"World of Warcraft",
"discord",
"twitch",
"youtube",
"Mariano Bondar",
"Paren La Mano",
"Alfred (Batman)",
"freddy krueger",
"jason voorhees",
"michael myers",
"chucky",
"pennywise",
"Silvestre Stallone",
"Arnold Schwarzenegger",
"Rapido y Furioso",
"Scary Movie"
];

// 1. Definir la forma de los datos
interface GameContextType {
    totalJugadores: number;
    setTotalJugadores: React.Dispatch<React.SetStateAction<number>>;
    totalImpostores: number;
    setTotalImpostores: React.Dispatch<React.SetStateAction<number>>;
    currentPlayer: number;
    impostorIDs: number[];       
    crewmateKeyword: string;
    handleStartGame: () => void;
    handleNextPlayer: () => void;
}

const GameContext = createContext<GameContextType | undefined>(undefined);

// 2. Proveedor (Provider)
interface GameProviderProps {
    children: ReactNode;
}

export const GameProvider: React.FC<GameProviderProps> = ({ children }) => {
    const router = useRouter();

  // ESTADOS CENTRALIZADOS
    const [totalJugadores, setTotalJugadores] = useState(MIN_JUGADORES);
    const [totalImpostores, setTotalImpostores] = useState(1);
    const [currentPlayer, setCurrentPlayer] = useState(1);
    const [impostorIDs, setImpostorIDs] = useState<number[]>([]);
    const [crewmateKeyword, setCrewmateKeyword] = useState<string>(KEYWORDS[0]);

  // --- FUNCIÓN DE INICIO (Se llama desde index.tsx) ---
    const handleStartGame = () => {
      const randomIndex = Math.floor(Math.random() * KEYWORDS.length); 
      setCrewmateKeyword(KEYWORDS[randomIndex]); // Asigna la palabra seleccionada al estado
      // 1. Inicializa y asigna el impostor
      const allPlayers = Array.from({ length: totalJugadores }, (_, i) => i + 1);
      const shuffledPlayers = allPlayers.sort(() => 0.5 - Math.random());
      const selectedImpostorIDs = shuffledPlayers.slice(0, totalImpostores);

      setImpostorIDs(selectedImpostorIDs);
      setCurrentPlayer(1);
    
      // Navega a la pantalla donde comienza la asignación de roles
      router.push("/tarjeta");
    };

  // --- FUNCIÓN DE AVANCE (Se llama desde tarjeta.tsx) ---
    const handleNextPlayer = () => {
    const nextPlayer = currentPlayer + 1;
    
    // 3. Condición de Fin de Asignación (Fase 3)
    if (nextPlayer > totalJugadores) {
      setCurrentPlayer(0); // Reinicia para seguridad
      router.push("/fase3"); // Navega a la pantalla final
    return;
    }

    // 2. Avanzar al siguiente jugador
    setCurrentPlayer(nextPlayer);
    };

    return (
        <GameContext.Provider value={{
            totalJugadores,
            setTotalJugadores,
            totalImpostores,
            setTotalImpostores,
            currentPlayer,
            handleStartGame,
            handleNextPlayer,
            impostorIDs,
            crewmateKeyword,
        }}>
            {children}
        </GameContext.Provider>
    );
};

// 3. Hook para usar el Contexto
export const useGame = () => {
    const context = useContext(GameContext);
    if (context === undefined) {
    throw new Error('useGame debe ser usado dentro de un GameProvider');
    }
    return context;
};