export interface CategoryItem {
    id: string;
    nombre: string;
    items: string[];
    imagen: any;
}

export const CATEGORIAS_DISPONIBLES: CategoryItem[] = [
    { id: "1", nombre: "Personas Famosas",imagen: require("../../assets/PersonasFamosas.png"), items: [
        "Messi",
        "Maradona",
        "Ricardo Fort",
        "Coscu",
        "Duki",
        "Bizarrap",
        "Wos",
        "Trueno",
        "Khea",
        "Paulo Londra",
        "L-Gante",
        "Tini Stoessel",
        "Moria Casán",
        "Mirta Legrand",
        "Susana Giménez",
        "Tinelli",
        "Guido Kaczka",
        "Don Cornelio",
        "Ricardo Iorio",
        "Pappo",
        "Charly García",
        "Fito Páez",
        "Spinetta",
        "Andrés Calamaro",
        "Gustavo Cerati",
        "Ibai",
        "AuronPlay",
        "Rubius",
        "Vegetta777",
        "Willyrex",
        "German Garmendia",
        "JulioProfe",
        "Martin Sirio (La Faraona)",
        "Momo (Influencer Argentino)",
        "Marito Baracus (Influencer Argentino)",
        "Flor Vigna",
        "Nati Jota",
        "Lit Killah",
        "Nicki Nicole",
        "Cazzu",
        "Tiago PZK",
        "Ysy A",
        "Coscu Army Kid",
        "Manu Ginobili",
        "PewDiePie",
        "MrBeast",
        "Kai Cenat",
        "Speed",
        "Pokimane",
        "Amouranth",
        "Davo",
        "La Cobra",
        "Macri",
        "Mariano Bondar",
        "Paren La Mano",
        "Michael Jackson",
        "Freddie Mercury",
        "Madonna",
        "Elvis Presley",
        "Bob Marley",
        "John Lennon",
        "Paul McCartney",
        "Taylor Swift",
        "Bad Bunny",
        "Lady Gaga",
        "Eminem",
        "Kurt Cobain",
        "Axel Rose",
        "Slash",
        "Shakira",
        "Daddy Yankee",
        "Residente",
        "Amy Winehouse",
        "David Bowie",
        "Prince",
        "The Weeknd",
        "Ariana Grande",
        "Billie Eilish",
        "Dua Lipa",
        "Snoop Dogg",
        "Tupac",
        "Beyoncé",
        "Rihanna",
        "Adele",
        "Elton John",
        "Stevie Wonder",
        "Britney Spears",
        "Justin Bieber",
        "Katy Perry",
        "Mick Jagger",
        "Ozzy Osbourne",
        "Daft Punk",
        "Selena Gomez",
        "Harry Styles",
        "Cristiano Ronaldo",
        "Pelé",
        "Neymar",
        "Michael Jordan",
        "LeBron James",
        "Kobe Bryant",
        "Usain Bolt",
        "Serena Williams",
        "Roger Federer",
        "Rafael Nadal",
        "Muhammad Ali",
        "Tom Brady",
        "Tiger Woods",
        "Mike Tyson",
        "Albert Einstein",
        "Stephen Hawking",
        "Leonardo da Vinci",
        "Steve Jobs",
        "Bill Gates",
        "Elon Musk",
        "Mark Zuckerberg",
        "Che Guevara",
        "Pablo Escobar",
        "Chuck Norris",
        "Tom Holland",
        "Quentin Tarantino",
        "Steven Spielberg",
        "Martin Scorsese",
        "Cristina Kirchner",
        "Javier Milei",
        "Guillermo Francella",
        "Diego Capusotto",
        "Peter Capusotto",
        "Indio Solari",
        "Wanda Nara",
        "Zaira Nara",
        "Spreen",
        "Santi Maratea",
        "Lali Espósito",
        "María Becerra",
        "Emilia Mernes",
        "Ángel Di María",
        "Dibu Martínez",
        "Scaloni",
        "Luis Miguel",
        "Ricky Martin",
        "Chayanne",
        "Celia Cruz",
        "Marc Anthony",
        "Don Omar",
        "Wisin",
        "Yandel",
        "Novak Djokovic",
        "Riquelme",
        "Carlos Tevez",
        "Kun Agüero",
        "Ayrton Senna",
        "Michael Schumacher",
        "Kim Kardashian",
        "Kylie Jenner",
        "Gordon Ramsay",
        "Martitegui",
        "Donnato",
        "Luis Ventura",
        "Backstreet Boys",
        "Christina Aguilera",
        "Linkin Park",
        "Red Hot Chili Peppers",
        "Oprah Winfrey",
        "Mafalda",
        "Frida Kahlo (artista)",
        "Leonardo da Vinci",
        "Juana de Arco",
        "Icardi (futbolista)",
        "Dios (figura religiosa)",
        "Jesús (figura religiosa)",
        "Buda (figura religiosa)",
        "Mbappé",
        "Cristian Castro",
        "Nelson Mandela",
        "Adolf Hitler ",
        "Cleopatra",
        "Julio César",
        "Mahatma Gandhi"
    ]},
    { id: "2", nombre: "Series Y Peliculas",imagen: require("../../assets/SeriesYPeliculas.png"), items: [
        "John Wick",
        "Morpheus",
        "Marty McFly",
        "Doc Brown",
        "Biff Tannen",
        "Tony Montana",
        "Jack Sparrow",
        "Will Turner",
        "Elizabeth Swann",
        "Davy Jones",
        "Rick Grimes",
        "Daryl",
        "Michonne",
        "Negan",
        "The Walking Dead",
        "Walter White",
        "Jesse Pinkman",
        "Saul Goodman",
        "Gustavo Fring",
        "Volver al Futuro",
        "El Padrino",
        "Scarface",
        "Freddy Krueger",
        "Jason Voorhees",
        "Michael Myers",
        "Chucky",
        "Pennywise",
        "Silvestre Stallone",
        "Arnold Schwarzenegger",
        "Rápido y Furioso",
        "Dominic Toretto",
        "Brian O'Connel (Rápidos y furiosos)",
        "Scary Movie",
        "Misión Imposible",
        "James Bond",
        "Scream",
        "Hannibal Lecter",
        "MacGyver",
        "El Zorro",
        "Sargento García",
        "He-Man",
        "Forrest Gump",
        "E.T.",
        "Mi Pobre Angelito",
        "Willy Wonka",
        "El Club de la pelea",
        "El extraño mundo de Jack",
        "El Grinch",
        "Terminator",
        "Alien",
        "Depredador",
        "Rambo", 
        "Rocky Balboa",
        "Jack (Titanic)",
        "Rose (Titanic)",
        "Friends",
        "The Office",
        "Michael Scott (The Office)",
        "Dwight (The Office)",
        "Jim (The Office)",
        "Pam (The Office)",
        "Sheldon (The Big Bang Theory)",
        "Leonard (The Big Bang Theory)",
        "Penny (The Big Bang Theory)",
        "Howard (The Big Bang Theory)",
        "Barney (How I Met Your Mother)",
        "Ted (How I Met Your Mother)",
        "Robin (How I Met Your Mother)",
        "How I Met Your Mother",
        "Dr. House",
        "Darth Vader (Star Wars)",
        "Luke (Star Wars)",
        "Yoda (Star Wars)",
        "Han Solo (Star Wars)",
        "Chewbacca (Star Wars)",
        "Leia (Star Wars)",
        "R2-D2 (Star Wars)",
        "C-3PO (Star Wars)",
        "Obi-Wan (Star Wars)",
        "Anakin (Star Wars)",
        "Eleven (Stranger Things)",
        "Hopper (Stranger Things)",
        "Dustin (Stranger Things)",
        "Steve Harrington (Stranger Things)",
        "Vecna (Stranger Things)",
        "Jon Snow (Game of Thrones)",
        "Daenerys (Game of Thrones)",
        "Tyrion (Game of Thrones)",
        "Arya (Game of Thrones)",
        "Cersei (Game of Thrones)",
        "Geralt (The Witcher)",
        "Ciri (The Witcher)",
        "Yennefer (The Witcher)",
        "Homelander",
        "Omni-Man",
        "Harry Potter",
        "Hermione Granger",
        "Ron Weasley",
        "Albus Dumbledore",
        "Severus Snape",
        "Lord Voldemort",
        "Gandalf",
        "Gollum",
        "Pepe Argento",
        "Moni Argento",
        "Coki Argento",
        "Paola Argento",
        "Dardo Fuseneco",
        "María Elena Fuseneco",
        "Yayo Guridi",
        "Pachu Peña",
        "Migue Granados"
    ]},
    { id: "3", nombre: "Super Heroes",imagen: require("../../assets/SuperHeroes.png"), items: [
        "Joker",
        "Robin",
        "Bane",
        "Superman",
        "Wonder Woman",
        "Flash",
        "Aquaman",
        "Iron Man",
        "Captain America",
        "Hulk",
        "Black Widow",
        "Spiderman",
        "Venom",
        "Wolverine",
        "Magneto",
        "Professor X",
        "El Caballero de la Noche",
        "El Hombre de Acero",
        "La Liga de la Justicia",
        "Mujer Maravilla",
        "Linterna Verde",
        "Batman Inicia",
        "El Joker",
        "Escuadrón Suicida",
        "Deadpool",
        "Logan",
        "X-Men",
        "Capitán América: El Primer Vengador",
        "Thor",
        "Guardianes de la Galaxia",
        "Avengers: Los Vengadores",
        "Doctor Strange: Hechicero Supremo",
        "Alfred (Batman)",
        "Lex Luthor",
        "Catwoman",
        "Pingüino",
        "Acertijo",
        "Dos Caras",
        "Harley Quinn",
        "Batman",
        "Green Lantern",
        "Doctor Strange",
        "Hawkeye",
        "Ant-Man",
        "Black Panther",
        "Iron Man",
        "Captain America",
        "Star-Lord",
        "Gamora",
        "Drax",
        "Rocket Raccoon",
        "Groot",
        "Vision",
        "Wanda Maximoff",
        "Thanos",
        "Loki",
        "Doctor Octopus",
        "Duende Verde",
        "Nick Fury",
        "Deadpool",
        "Logan",
        "X-Men",
        "Spider-Man: De Regreso a Casa"
    ]},
    {id: "4", nombre: "Series animadas",imagen: require("../../assets/SeriesAnimadas.png"), items: [
        "Alf",
        "Homero",
        "Marge",
        "Bart",
        "Lisa",
        "Maggie",
        "Milhouse",
        "Ned Flanders",
        "Apu",
        "Mr. Burns",
        "Moe",
        "Shrek",
        "Burro",
        "Fiona",
        "Gato con Botas",
        "Buzz Lightyear",
        "Woody",
        "Andy (Toy Story)",
        "Sid",
        "Elsa",
        "Anna",
        "Olaf",
        "Sven",
        "Simba (El Rey León)",
        "Nala (El Rey León)",
        "Mufasa (El Rey León)",
        "Aladdín (Aladdín)",
        "Jazmín (Aladdín)",
        "Genio (Aladdín)",
        "Jafar (Aladdín)",
        "Peter Pan (Peter Pan)",
        "Campanita (Peter Pan)",
        "Capitán Garfio (Peter Pan)",
        "Winnie the Pooh",
        "Piglet (Winnie the Pooh)",
        "Tigger (Winnie the Pooh)",
        "Eeyore (Winnie the Pooh)",
        "Pinocho (Pinocho)",
        "Geppetto (Pinocho)",
        "Dumbo (Dumbo)",
        "Timothy (Dumbo)",
        "Bambi (Bambi)",
        "Hada Azul (Pinocho)",
        "Aurora (La Bella Durmiente)",
        "Maléfica (La Bella Durmiente)",
        "Felipe (La Bella Durmiente)",
        "Cenicienta (Cenicienta)",
        "Hada Madrina (Cenicienta)",
        "Anastasia (Cenicienta)",
        "Ariel (La Sirenita)",
        "Sebastián (La Sirenita)",
        "Flounder (La Sirenita)",
        "Ursula (La Sirenita)",
        "Tarzán (Tarzán)",
        "Jane (Tarzán)",
        "Clayton (Tarzán)",
        "Tiana (La Princesa y el Sapo)",
        "Naveen (La Princesa y el Sapo)",
        "Doctor Facilier (La Princesa y el Sapo)",
        "Rapunzel (Enredados)",
        "Flynn Rider (Enredados)",
        "Maximus (Enredados)",
        "Gothel (Enredados)",
        "Ralph (Ralph el Demoledor)",
        "El Rey León",
        "Aladdín",
        "La Sirenita",
        "La Bella y la Bestia",
        "La Bella Durmiente",
        "Blanca Nieves y los Siete Enanos",
        "Pinocho",
        "Dumbo",
        "Bambi",
        "Cenicienta",
        "Peter Pan",
        "Winnie the Pooh",
        "Vanellope (Ralph el Demoledor)",
        "Miguel (Coco)",
        "Héctor (Coco)",
        "Mama Coco",
        "Remy (Ratatouille)",
        "Linguini (Ratatouille)",
        "Colette (Ratatouille)",
        "Anton Ego (Ratatouille)",
        "Merida (Valiente)",
        "Rey Fergus (Valiente)",
        "Bolt (Bolt)",
        "La Dama y el Vagabundo",
        "Los Aristogatos",
        "Robin Hood",
        "Taron y el Caldero Mágico",
        "El Zorro y el Sabueso",
        "Oliver y su Pandilla",
        "La Princesa y el Sapo",
        "Enredados",
        "Valiente",
        "Frozen",
        "Moana",
        "Zootopia",
        "Intensamente",
        "Coco",
        "Soul",
        "Un Gran Dinosaurio",
        "Ratatouille",
        "Cars",
        "Buscando a Nemo",
        "Monsters Inc",
        "Toy Story",
        "Los Increíbles",
        "Up: Una Aventura de Altura",
        "Wall-E",
        "Unidos",
        "Elementos",
        "Luca",
        "Gravity Falls",
        "Steven Universe",
        "Hora de Aventura",
        "Un Show Más",
        "Clarence",
        "Los Padrinos Mágicos",
        "Bob Esponja",
        "Patricio Estrella",
        "Calamardo Tentáculos",
        "Rick Sanchez",
        "Morty Smith (Rick y Morty)",
        "Finn el Humano",
        "Jake el Perro",
        "Mordecai",
        "Rigby",
        "Gumball Watterson",
        "Darwin Watterson",
        "Coraje (El perro cobarde)",
        "Dexter",
        "Dee Dee (Dexter)",
        "Burbuja",
        "Bombón",
        "Bellota",
        "Mojo Jojo",
        "Johnny Bravo",
        "Scooby-Doo",
        "Shaggy (Scooby-Doo)",
        "Tom (Tom y Jerry)",
        "Jerry (Tom y Jerry)",
        "Bugs Bunny",
        "Pato Lucas",
        "Porky",
        "Silvestre",
        "Piolín",
        "Correcaminos",
        "Coyote",
        "Demonio de Tazmania",
        "Pantera Rosa",
        "Garfield",
        "Snoopy",
        "Charlie Brown",
        "Popeye, Olivia, Brutus",
        "Cartman (South Park)",
        "Stan Marsh (South Park)",
        "Kyle (South Park)",
        "Kenny (South Park)",
        "Peter Griffin (Family Guy)",
        "Stewie Griffin (Family Guy)",
        "Brian Griffin (Family Guy)",
        "Ed, Edd y Eddy",
        "Scar (El Rey León)",
        "Cruella de Vil",
        "Hades (Hércules)",
        "Papá Pitufo",
        "Hello Kitty",
        "El Chavo del 8",
        "Don Ramón",
        "Quico",
        "La Chilindrina",
        "Señor Barriga",
        "Profesor Jirafales",
        "Doña Florinda"
    ]},
    { id: "5", nombre: "Anime",imagen: require("../../assets/Anime.png"), items: [
        "Light Yagami (Death Note)",
        "L (Death Note)",
        "Misa Amane (Death Note)",
        "Near (Death Note)",
        "Yagami Soichiro (Death Note)",
        "Tanjiro Kamado (Demon Slayer)",
        "Nezuko Kamado (Demon Slayer)",
        "Zenitsu Agatsuma (Demon Slayer)",
        "Inosuke Hashibira (Demon Slayer)",
        "Gyu Tomioka (Demon Slayer)",
        "Eren Jaeger (Attack on Titan)",
        "Mikasa Ackerman (Attack on Titan)",
        "Armin Arlert (Attack on Titan)",
        "Levi Ackerman (Attack on Titan)",
        "Erwin Smith (Attack on Titan)",
        "Naruto Uzumaki (Naruto)",
        "Hinata Hyuga (Naruto)",
        "Gaara (Naruto)",
        "Jiraiya (Naruto)",
        "Sakura Haruno (Naruto)",
        "Ichigo Kurosaki (Bleach)",
        "Luffy (One Piece)",
        "Zoro (One Piece)",
        "Nami (One Piece)",
        "Sanji (One Piece)",
        "Chopper (One Piece)",
        "Robin (One Piece)",
        "Usopp (One Piece)",
        "Brook (One Piece)",
        "Franky (One Piece)",
        "Gon (Hunter x Hunter)",
        "Killua (Hunter x Hunter)",
        "Kurapika (Hunter x Hunter)",
        "Edward Elric (Fullmetal Alchemist)",
        "Alphonse Elric (Fullmetal Alchemist)",
        "Roy Mustang (Fullmetal Alchemist)",
        "Mi Vecino Totoro",
        "El Castillo Ambulante",
        "El Viaje de Chihiro",
        "La Princesa Mononoke",
        "Goku",
        "Vegeta",
        "Piccolo",
        "Frieza",
        "Cell",
        "Majin Buu",
        "Naruto",
        "Sasuke",
        "Sakura",
        "Kakashi",
        "Jiraiya",
        "Ichigo"
    ]},
    {id: "6", nombre: "Videojuegos",imagen: require("../../assets/VideoJuegos.png"), items: [
        "Hollow Knight",
        "Celeste",
        "Stardew Valley",
        "Undertale",
        "Hades",
        "GTA San Andreas",
        "GTA V",
        "The Witcher 3",
        "Red Dead Redemption 2",
        "Cyberpunk 2077",
        "Assassin's Creed",
        "Minecraft",
        "Fortnite",
        "League of Legends",
        "Counter Strike",
        "CJ",
        "Tommy Vercetti",
        "Niko Bellic",
        "Kratos",
        "Atreus",
        "Zeus",
        "Play 2",
        "PES 06",
        "Resident Evil 4",
        "Silent Hill",
        "Metal Gear Solid",
        "Final Fantasy VII",
        "Steam",
        "Epic Games",
        "Ubisoft",
        "EA Games",
        "Discord",
        "Twitch",
        "YouTube",
        "World of Warcraft",
        "Mario Bros",
        "Luigi",
        "Peach",
        "Bowser",
        "Yoshi",
        "Donkey Kong",
        "Link",
        "Zelda",
        "Pikachu",
        "Ash",
        "Charizard",
        "Mewtwo",
        "Kirby",
        "Sonic",
        "Pac-Man",
        "Master Chief",
        "Lara Croft",
        "Leon (Resident Evil)",
        "Ada (Resident Evil)",
        "Jill Valentine (Resident Evil)",
        "Chris (Resident Evil)",
        "Wesker (Resident Evil)",
        "Sub-Zero (Mortal Kombat)",
        "Scorpion (Mortal Kombat)",
        "Liu Kang (Mortal Kombat)",
        "Raiden (Mortal Kombat)",
        "Ryu (Street Fighter)",
        "Ken (Street Fighter)",
        "Chun-li (Street Fighter)",
        "Mega Man",
        "Crash Bandicoot",
        "Spyro",
        "Ezio Auditore",
        "Arthur Morgan",
        "John Marston",
        "Ciri",
        "Yennefer",
        "Geralt de Rivia",
        "Steve",
        "Creeper (Minecraft)",
        "Trevor (GTA V)",
        "Michael (GTA V)",
        "Franklin (GTA V)",
        "Big Smoke (GTA)"
    ]},
    {id: "7", nombre: "Objetos",imagen: require("../../assets/Gemini_Generated_Image_rabyj8rabyj8raby.png"), items: ["Cerveza",
        "Gorra",
        "Carpa",
        "Llave",
        "Anillo",
        "Tenedor",
        "Cuchillo",
        "Vaso",
        "Plato",
        "Silla",
        "Mesa",
        "Lámpara",
        "Botella",
        "Zapatos",
        "Reloj",
        "Libro",
        "Bolígrafo",
        "Cuaderno",
        "Teléfono",
        "Computadora",
        "Monitor",
        "Teclado",
        "Ratón",
        "Cable",
        "Batería",
        "Martillo",
        "Clavo",
        "Tornillo",
        "Destornillador",
        "Sierra",
        "Hacha",
        "Pala",
        "Escoba",
        "Trapeador",
        "Balde",
        "Jarra",
        "Taza",
        "Cuchara",
        "Servilleta",
        "Toalla",
        "Jabón",
        "Cepillo",
        "Peine",
        "Espejo",
        "Perfume",
        "Champú",
        "Crema",
        "Almohada",
        "Manta",
        "Sábana",
        "Colchón",
        "Armario",
        "Cajón",
        "Percha",
        "Alfombra",
        "Cortina",
        "Ventana",
        "Puerta",
        "Pared",
        "Techo",
        "Suelo",
        "Florero",
        "Planta",
        "Maceta",
        "Pintura",
        "Brocha",
        "Lienzo",
        "Radio",
        "Altavoz",
        "Micrófono",
        "Cámara",
        "Bolsa",
        "Cartera",
        "Mochila",
        "Gafas",
        "Bufanda",
        "Guantes",
        "Sombrero",
        "Chaqueta",
        "Pantalón",
        "Camisa",
        "Vestido",
        "Calcetín",
        "Corbata",
        "Bikini",
        "Sombrilla",
        "Tumbona",
        "Pelota",
        "Globo",
        "Cuerda",
        "Cometa",
        "Patines",
        "Bicicleta",
        "Casco",
        "Monopatín",
        "Patineta",
        "Piscina",
        "Flotador",
        "Gafas de buceo",
        "Aletas",
        "Caña de pescar",
        "Red",
        "Cubo",
        "Arena",
        "Piedra",
        "Rama",
        "Hoja",
        "Flor",
        "Fruta",
        "Verdura",
        "Pan",
        "Queso",
        "Leche",
        "Huevo",
        "Carne",
        "Pescado",
        "Arroz",
        "Pasta",
        "Azúcar",
        "Sal",
        "Pimienta",
        "Aceite",
        "Vinagre",
        "Miel",
        "Café",
        "Té",
        "Chocolate",
        "Galleta",
        "Caramelo",
        "Jugo",
        "Refresco",
        "Vino",
        "Copa",
        "Bandera",
        "Mapa",
        "Brújula",
        "Binoculares",
        "Linterna",
        "Cerilla",
        "Mechero",
        "Vela",
        "Cenicero",
        "Cigarro",
        "Pipa",
        "Tijera",
        "Pegamento",
        "Cinta adhesiva",
        "Grapa",
        "Grapadora",
        "Sacapuntas",
        "Goma de borrar",
        "Lápiz",
        "Rotulador",
        "Pizarra",
        "Tiza",
        "Borrador",
        "Regla",
        "Compás",
        "Transportador",
        "Calculadora",
        "Agenda",
        "Calendario",
        "Tarjeta",
        "Billete",
        "Moneda",
        "Billetera",
        "Cartera de mano",
        "Llavero",
        "Pulsera",
        "Collar",
        "Pendiente",
        "Gema",
        "Oro",
        "Plata",
        "Bronce",
        "Cobre",
        "Hierro",
        "Acero",
        "Aluminio",
        "Cristal",
        "Madera",
        "Plástico",
        "Goma",
        "Tela",
        "Papel",
        "Cartón",
        "Revista",
        "Periódico",
        "Folletos",
        "Postal",
        "Sello",
        "Sobre",
        "Buzón",
        "Campana",
        "Silbato",
        "Tambor",
        "Guitarra",
        "Piano",
        "Flauta",
        "Violín",
        "Trompeta",
        "Saxofón",
        "Bajo",
        "Batería musical",
        "Micrófono de pie",
        "Atril",
        "Partitura",
        "Auriculares",
        "Altavoces",
        "Grabadora",
        "Disco",
        "Cassette",
        "CD",
        "DVD",
        "Videojuego",
        "Consola",
        "Mando",
        "Joystick",
        "Máquina de escribir",
        "Telégrafo",
        "Fax",
        "Impresora",
        "Escáner",
        "Fotocopiadora",
        "Caja fuerte",
        "Alarma",
        "Detector de humo",
        "Extintor",
        "Botiquín",
        "Venda",
        "Gasas",
        "Alcohol",
        "Medicamento",
        "Jeringa",
        "Termómetro",
        "Tensiómetro",
        "Tijeras médicas",
        "Ambulancia (modelo)",
        "Coche (modelo)",
        "Avión (modelo)",
        "Barco (modelo)",
        "Tren (modelo)",
        "Autobús (modelo)",
        "Camión (modelo)",
        "Moto (modelo)",
        "Barco de vela",
        "Remo",
        "Ancla",
        "Salvavidas",
        "Boyas",
        "Manguera",
        "Regadera",
        "Aspersor",
        "Tractor (modelo)",
        "Semilla",
        "Fertilizante",
        "Cesta",
        "Canasta",
        "Paraguas",
        "Impermeable",
        "Botas de agua",
        "Chimenea",
        "Leña",
        "Estufa",
        "Radiador",
        "Ventilador",
        "Aire acondicionado",
        "Termostato",
        "Grifo",
        "Ducha",
        "Bañera",
        "Inodoro",
        "Lavabo",
        "Bidé",
        "Esponja",
        "Pastilla de jabón",
        "Toallero",
        "Bata",
        "Pijama",
        "Babero",
        "Pañal",
        "Biberón",
        "Chupete",
        "Sonajero",
        "Triciclo",
        "Columpio",
        "Tobogán",
        "Balancín",
        "Mascota (collar)",
        "Pecera",
        "Jaula",
        "Correa",
        "Hueso (de juguete)",
        "Comida para perro",
        "Rascador de gato",
        "Arenero",
        "Pez de goma",
        "Pájaro (juguete)",
        "Hamaca",
        "Mecedora",
        "Banco",
        "Poste",
        "Farola",
        "Semáforo",
        "Señal de tráfico",
        "Esquina",
        "Adoquín",
        "Asfalto",
        "Ladrillo",
        "Cemento",
        "Grava",
        "Piedra preciosa",
        "Diamante (imitación)",
        "Esmeralda (imitación)",
        "Rubí (imitación)",
        "Zafiro (imitación)",
        "Ópalo (imitación)",
        "Máscara",
        "Disfraz",
        "Peluca",
        "Maquillaje",
        "Kit de costura",
        "Aguja",
        "Hilo",
        "Dedal",
        "Botón",
        "Cremallera",
        "Parche",
        "Encaje",
        "Máquina de coser",
        "Patrón",
        "Bobina",
        "Tiza de sastre",
        "Prensa",
        "Tornillo de banco",
        "Gato hidráulico",
        "Llave inglesa",
        "Alicates",
        "Sierra de calar",
        "Taladro",
        "Broca",
        "Lima",
        "Serrucho",
        "Escalera",
        "Andamio",
        "Cuerda de seguridad",
        "Guantes de trabajo",
        "Casco de seguridad",
        "Gafas de seguridad",
        "Cinturón de herramientas",
        "Nivel",
        "Plomada",
        "Metro (cinta)",
        "Caballete",
        "Viga",
        "Tubo",
        "Ladrillo de LEGO",
        "Muñeca",
        "Peluche",
        "Puzle",
        "Juego de mesa",
        "Dados",
        "Ficha",
        "Baraja de cartas",
        "Domino",
        "Ajedrez (pieza)",
        "Damas (pieza)",
        "Canicas",
        "Arcilla",
        "Plastilina",
        "Acuarelas",
        "Carboncillo",
        "Gis",
        "Aerógrafo",
        "Cabezal de ducha",
        "Desagüe",
        "Sifón",
        "Bomba de aire",
        "Inflador",
        "Válvula",
        "Neumático",
        "Rueda",
        "Motor (modelo)",
        "Bujía",
        "Filtro",
        "Aceite de motor",
        "Anticongelante",
        "Embudo",
        "Gato de coche",
        "Llave de rueda",
        "Triángulo de emergencia",
        "Chaqueta reflectante",
        "Rueda de repuesto",
        "Bocina",
        "Parabrisas",
        "Limpiaparabrisas",
        "Faro",
        "Intermitente",
        "Retrovisor",
        "Matrícula",
        "Depósito de gasolina",
        "Manguera de gasolina",
        "Surtidor",
        "Ticket",
        "Caja registradora",
        "Escáner de código",
        "Báscula",
        "Cesta de la compra",
        "Carrito de la compra",
        "Etiqueta de precio",
        "Periódico (viejo)",
        "Calendario de pared",
        "Alfiler",
        "Imán",
        "Bote de basura",
        "Reciclaje (contenedor)",
        "Aspiradora",
        "Pulidora",
        "Abrillantador",
        "Cera",
        "Detergente",
        "Suavizante",
        "Blanqueador",
        "Desinfectante",
        "Ambientador",
        "Incienso",
        "Vaporizador",
        "Regulador",
        "Temporizador",
        "Cronómetro",
        "Cronógrafo",
        "Metrónomo",
        "Brújula de bolsillo",
        "Telescopio",
        "Microscopio",
        "Lupa",
        "Diapositiva",
        "Pipeta",
        "Tubo de ensayo",
        "Matraz",
        "Bureta",
        "Mortero",
        "Probeta",
        "Balanza de precisión",
        "Mechero de Bunsen",
        "Horno",
        "Fogón",
        "Microondas",
        "Refrigerador",
        "Congelador",
        "Lavadora",
        "Secadora",
        "Lavavajillas",
        "Tostadora",
        "Batidora",
        "Licuadora",
        "Exprimidor",
        "Cafetera",
        "Hervidor",
        "Olla",
        "Sartén",
        "Wok",
        "Cazuela",
        "Asadera",
        "Molde",
        "Rallador",
        "Pelador",
        "Triturador",
        "Espátula",
        "Cucharón",
        "Colador",
        "Escurridor",
        "Tabla de cortar",
        "Delantal",
        "Manopla de horno",
        "Rodillo",
        "Recetario",
        "Especiero",
        "Tarro",
        "Contenedor",
        "Fiambrera",
        "Nevera portátil",
        "Termo",
        "Cantimplora",
        "Saco de dormir",
        "Esterilla",
        "Navaja suiza",
        "Kit de supervivencia",
        "Manta térmica",
        "Silbato de emergencia",
        "Radio portátil",
        "Panel solar (pequeño)",
        "Cargador",
        "Adaptador",
        "Enchufe",
        "Interruptor",
        "Fusible",
        "Caja de herramientas (vacía)",
        "Medidor de voltaje",
        "Soldador",
        "Estación de soldadura",
        "Lentes de aumento",
        "Pinzas",
        "Tornillo de mariposa",
        "Arandela",
        "Tuerca",
        "Tirador",
        "Bisagra",
        "Pomo",
        "Cerradura",
        "Candado",
        "Cadena",
        "Mosquetón",
        "Hebilla",
        "Cinturón",
        "Tirantes",
        "Gemelos (para camisa)",
        "Hombreras",
        "Gorro de lana",
        "Visera",
        "Pañuelo",
        "Diadema",
        "Coletero",
        "Horquilla",
        "Gomina",
        "Laca",
        "Secador de pelo",
        "Plancha de pelo",
        "Rizador",
        "Afeitadora",
        "Maquinilla de afeitar",
        "Brocha de afeitar",
        "Espuma de afeitar",
        "Aftershave",
        "Loción",
        "Tónico",
        "Agua micelar",
        "Disco de algodón",
        "Hisopo",
        "Lima de uñas",
        "Cortauñas",
        "Esmalte de uñas",
        "Pintalabios",
        "Sombra de ojos",
        "Máscara de pestañas",
        "Colorete",
        "Brocha de maquillaje",
        "Bolsa de aseo",
        "Estuche",
        "Lapicero",
        "Tinta",
        "Sello (de goma)",
        "Almohadilla de tinta",
        "Clips",
        "Chincheta",
        "Imán de nevera",
        "Postal (sin escribir)",
        "Guía telefónica",
        "Directorio",
        "Diccionario",
        "Enciclopedia",
        "Atlas",
        "Globo terráqueo",
        "Póster",
        "Marco de fotos",
        "Álbum de fotos",
        "Trofeo",
        "Medalla",
        "Cinta",
        "Lazo",
        "Adorno",
        "Velas de cumpleaños",
        "Bengala",
        "Confeti",
        "Serpentina",
        "Piñata",
        "Juguete de cuerda",
        "Pistola de agua",
        "Dardos",
        "Diana",
        "Bolas de billar",
        "Taco de billar",
        "Red de tenis",
        "Raqueta",
        "Pelota de tenis",
        "Volante de bádminton",
        "Palo de golf",
        "Disco de frisbee",
        "Bate de béisbol",
        "Guante de béisbol",
        "Disco de hockey",
        "Puck de hockey",
        "Espada (juguete)",
        "Escudo (juguete)",
        "Máscara de buceo",
        "Tubo de snorkel",
        "Aletas de natación",
        "Gafas de natación",
        "Gorrito de natación",
        "Cronómetro deportivo",
        "Silbato de árbitro",
        "Banca de gimnasio",
        "Mancuerna",
        "Pesa rusa",
        "Esterilla de yoga",
        "Bloque de yoga",
        "Cinta de correr",
        "Bicicleta estática",
        "Comba",
        "Muleta",
        "Silla de ruedas",
        "Bastón",
        "Audífono",
        "Lentes de contacto",
        "Estuche de lentes",
        "Líquido de lentes",
        "Ojo de buey (ventana)",
        "Mirilla",
        "Trampilla",
        "Escotilla",
        "Pasamanos",
        "Barandilla",
        "Pérgola",
        "Cenador",
        "Hamaca de red",
        "Saco de boxeo",
        "Guantes de boxeo",
        "Casco de moto",
        "Rodillera",
        "Coderas",
        "Espaldera",
        "Piruleta",
        "Chicle",
        "Patata frita",
        "Kétchup",
        "Mostaza",
        "Mayonesa",
        "Salsa de tomate (lata)",
        "Atún (lata)",
        "Frijoles (lata)",
        "Conservas",
        "Encurtido",
        "Esponja de cocina",
        "Estropajo",
        "Salero",
        "Pimentero",
        "Especia (bote)",
        "Bolsa de basura",
        "Rollo de papel de cocina",
        "Rollo de papel higiénico",
        "Ambientador de baño",
        "Jabonera",
        "Vaso de cepillos",
        "Juguete de baño",
        "Patito de goma",
        "Burbujas (líquido)",
        "Bomba de baño",
        "Roca volcánica",
        "Concha",
        "Estrella de mar",
        "Coral (decoración)",
        "Pez de colores (juguete)",
        "Algoritmo (esquema)",
        "Fórmula (papel)",
        "Gráfico",
        "Diagrama",
        "Línea de tiempo",
        "Cubo de Rubik",
        "Puzzle 3D",
        "Máquina de pinball (modelo)",
        "Jukebox (modelo)",
        "Dispensador de chicles",
        "Monedero",
        "Hucha",
        "Comprobante",
        "Recibo",
        "Factura",
        "Menú",
        "Carta (restaurante)",
        "Ticket de metro",
        "Bono de autobús",
        "Plano de la ciudad",
        "Folleto turístico",
        "Guía de viaje",
        "Mapa de carreteras",
        "Libreta de direcciones",
        "Organizador de escritorio",
        "Revistero",
        "Paragüero",
        "Cubo de fregar",
        "Señal de 'Piso mojado'",
        "Cámara de seguridad (simulada)",
        "Megáfono",
        "Walkie-talkie",
        "Teléfono fijo",
        "Centralita",
        "Modem",
        "Router",
        "Antena",
        "Repetidor",
        "Disco duro externo",
        "Memoria USB",
        "CD regrabable",
        "Disquete",
        "Cinta de vídeo",
        "Proyector",
        "Pantalla de proyección",
        "Puntero láser",
        "Control remoto",
        "Bolsa de hielo (reutilizable)",
        "Mascara de oxígeno",
        "Nebulizador",
        "Andador",
        "Silla de oficina",
        "Archivador",
        "Carpeta",
        "Separador",
        "Fichero",
        "Etiqueta adhesiva",
        "Perforadora",
        "Cizalla",
        "Destructora de papel",
        "Soporte para libros",
        "Abrecartas",
        "Sellador de bolsas",
        "Dispensador de cinta",
        "Imán de herramienta",
        "Cinta métrica",
        "Nivel de burbuja",
        "Gafas de sol (en estuche)",
        "Pajarita",
        "Cubrepolvo (ropa)",
        "Bolsa de deporte",
        "Red de lavandería",
        "Pinza de tender",
        "Cesto de ropa sucia",
        "Burro de planchar",
        "Plancha de ropa",
        "Vaporizador de ropa",
        "Botón de pánico",
        "Sensor de movimiento",
        "Termostato inteligente",
        "Asistente de voz (dispositivo)",
        "Cargador inalámbrico",
        "Power bank",
        "Adaptador de viaje",
        "Etiqueta de equipaje",
        "Candado de viaje",
        "Kit de costura de viaje",
        "Linterna frontal",
        "Hornillo de camping",
        "Funda de móvil",
        "Protector de pantalla",
        "Soporte de móvil",
        "Anillo de luz (selfie)",
        "Trípode (pequeño)",
        "Disparador remoto",
        "Lente para móvil",
        "Micrófono de solapa",
        "Mini proyector",
        "Cable HDMI",
        "Adaptador USB-C",
        "Ladrón eléctrico",
        "Enchufe temporizador",
        "Bote de pintura (pequeño)",
        "Disolvente",
        "Lija",
        "Espátula de pintor",
        "Rodillo de pintura",
        "Cinta de carrocero",
        "Plástico protector",
        "Gafas de soldar",
        "Soplete (pequeño)",
        "Kit de reparación de pinchazos",
        "Cadena de bicicleta",
        "Bomba de inflado (pie)",
        "Parche de bicicleta",
        "Juego de llaves Allen",
        "Aceite lubricante",
        "Desengrasante",
        "Trapo de limpieza",
        "Aerosol",
        "Pegatina",
        "Chapa (pin)",
        "Insignia",
        "Medallón",
        "Medallón con foto",
        "Caja de música",
        "Globo de nieve",
        "Muñeco de acción",
        "Juego de tren eléctrico",
        "Coche de control remoto",
        "Robot (juguete)",
        "Bloques de madera",
        "Ábaco",
        "Reloj de arena",
        "Péndulo (modelo)",
        "Tierra (en maceta)",
        "Pizarra magnética",
        "Letra magnética",
        "Número magnético",
        "Caja de herramientas (metálica)",
        "Caja de galletas (vacía)",
        "Bolsa de papel",
        "Bolsa de tela",
        "Cuerda de saltar",
        "Palo de selfie",
        "Estabilizador (cámara)",
        "Disco de vinilo",
        "Aguja de tocadiscos",
        "Tocadiscos (modelo)",
        "Radiocasete",
        "Walkman",
        "Game Boy",
        "Cámara instantánea",
        "Película fotográfica",
        "Revelador (botella)",
        "Álbum de sellos",
        "Monedero de cuero",
        "Diario (con candado)",
        "Frasco de perfume vacío",
        "Vaso de chupito",
        "Abrebotellas",
        "Sacacorchos",
        "Enfriador de vino",
        "Hielera",
        "Pinzas para hielo",
        "Dispensador de agua",
        "Filtro de agua",
        "Bebedero (mascota)",
        "Comedero (mascota)",
        "Puerta de mascota",
        "Ropa de mascota",
        "Zapatillas de casa",
        "Zuecos",
        "Sandalias",
        "Chanclas",
        "Zapatos de tacón",
        "Botas",
        "Botines",
        "Bailarinas",
        "Mocasines",
        "Náuticos",
        "Esmoquin (percha)",
        "Frac (percha)",
        "Kimono (percha)",
        "Hanbok (percha)",
        "Sari (tela)",
        "Tocado",
        "Corona (de juguete)",
        "Cetro (de juguete)",
        "Guantes de seda",
        "Abanico",
        "Paipái",
        "Bolso de fiesta",
        "Caja de bombones (vacía)",
        "Galletas de la suerte",
        "Tetera",
        "Caldero (pequeño)",
        "Infusor",
        "Taza medidora",
        "Espátula de silicona",
        "Brocha de repostería",
        "Papel de horno",
        "Bandeja de cubitos",
        "Temporizador de cocina",
        "Pesas de cocina",
        "Libro de recetas (digital)",
        "Prensa de ajos",
        "Deshuesador",
        "Maza de carne",
        "Molinillo de café",
        "Termómetro de carne",
        "Juego de Fondue",
        "Rallador de nuez moscada",
        "Abrelatas",
        "Separador de yemas",
        "Dispenser de agua"
    ]}
];