export interface CategoryItem {
    id: string;
    nombre: string;
    items: string[];
    imagen: any;
}

export const CATEGORIAS_DISPONIBLES: CategoryItem[] = [
    { id: "1", nombre: "Personas Famosas",imagen: require("../assets/PersonasFamosas.png"), items: [
        "Messi",
        "Maradona",
        "Ricardo Fort",
        "Coscu",
        "Duki",
        "Bizarrap",
        "Wos",
        "Trueno",
        "Khea",
        "Paulo Londra",
        "L-Gante",
        "Tini Stoessel",
        "Moria Casán",
        "Mirta Legrand",
        "Susana Giménez",
        "Tinelli",
        "Guido Kaczka",
        "Don Cornelio",
        "Ricardo Iorio",
        "Pappo",
        "Charly García",
        "Fito Páez",
        "Spinetta",
        "Andrés Calamaro",
        "Gustavo Cerati",
        "Ibai",
        "AuronPlay",
        "Rubius",
        "Vegetta777",
        "Willyrex",
        "German Garmendia",
        "JulioProfe",
        "Martin Sirio (La Faraona)",
        "Momo (Influencer Argentino)",
        "Marito Baracus (Influencer Argentino)",
        "Flor Vigna",
        "Nati Jota",
        "Lit Killah",
        "Nicki Nicole",
        "Cazzu",
        "Tiago PZK",
        "Ysy A",
        "Coscu Army Kid",
        "Manu Ginobili",
        "PewDiePie",
        "MrBeast",
        "Kai Cenat",
        "Speed",
        "Pokimane",
        "Amouranth",
        "Davo",
        "La Cobra",
        "Macri",
        "Mariano Bondar",
        "Paren La Mano",
        "Michael Jackson",
        "Freddie Mercury",
        "Madonna",
        "Elvis Presley",
        "Bob Marley",
        "John Lennon",
        "Paul McCartney",
        "Taylor Swift",
        "Bad Bunny",
        "Lady Gaga",
        "Eminem",
        "Kurt Cobain",
        "Axel Rose",
        "Slash",
        "Shakira",
        "Daddy Yankee",
        "Residente",
        "Amy Winehouse",
        "David Bowie",
        "Prince",
        "The Weeknd",
        "Ariana Grande",
        "Billie Eilish",
        "Dua Lipa",
        "Snoop Dogg",
        "Tupac",
        "Notorious B.I.G.",
        "Beyoncé",
        "Rihanna",
        "Adele",
        "Elton John",
        "Stevie Wonder",
        "Britney Spears",
        "Justin Bieber",
        "Katy Perry",
        "Mick Jagger",
        "Ozzy Osbourne",
        "Daft Punk",
        "Selena Gomez",
        "Harry Styles",
        "Cristiano Ronaldo",
        "Pelé",
        "Neymar",
        "Michael Jordan",
        "LeBron James",
        "Kobe Bryant",
        "Usain Bolt",
        "Serena Williams",
        "Roger Federer",
        "Rafael Nadal",
        "Muhammad Ali",
        "Tom Brady",
        "Tiger Woods",
        "Mike Tyson",
        "Albert Einstein",
        "Stephen Hawking",
        "Leonardo da Vinci",
        "Steve Jobs",
        "Bill Gates",
        "Elon Musk",
        "Mark Zuckerberg",
        "Che Guevara",
        "Pablo Escobar",
        "Chuck Norris",
        "Tom Holland",
        "Quentin Tarantino",
        "Steven Spielberg",
        "Martin Scorsese",
        "Cristina Kirchner",
        "Javier Milei",
        "Guillermo Francella",
        "Diego Capusotto",
        "Peter Capusotto",
        "Indio Solari",
        "Wanda Nara",
        "Zaira Nara",
        "Spreen",
        "Santi Maratea",
        "Lali Espósito",
        "María Becerra",
        "Emilia Mernes",
        "Ángel Di María",
        "Dibu Martínez",
        "Scaloni",
        "Luis Miguel",
        "Ricky Martin",
        "Chayanne",
        "Celia Cruz",
        "Marc Anthony",
        "Don Omar",
        "Wisin",
        "Yandel",
        "Novak Djokovic",
        "Riquelme",
        "Carlos Tevez",
        "Kun Agüero",
        "Ayrton Senna",
        "Michael Schumacher",
        "Kim Kardashian",
        "Kylie Jenner",
        "Gordon Ramsay",
        "Martitegui",
        "Donnato",
        "Luis Ventura",
        "Backstreet Boys",
        "Christina Aguilera",
        "Linkin Park",
        "Red Hot Chili Peppers",
        "Oprah Winfrey",
        "Mafalda",
        "Frida Kahlo (artista)",
        "Leonardo da Vinci",
        "Juana de Arco",
        "Icardi (futbolista)",
        "Dios (figura religiosa)",
        "Jesús (figura religiosa)",
        "Buda (figura religiosa)",
        "Mbappé",
        "Cristian Castro",
        "Nelson Mandela",
        "Adolf Hitler ",
        "Cleopatra",
        "Julio César",
        "Mahatma Gandhi"
    ]},
    { id: "2", nombre: "Series Y Peliculas",imagen: require("../assets/SeriesYPeliculas.png"), items: [
        "John Wick",
        "Neo",
        "Trinity",
        "Morpheus",
        "Marty McFly",
        "Doc Brown",
        "Biff Tannen",
        "Tony Montana",
        "Vito Corleone",
        "Michael Corleone",
        "Fredo Corleone",
        "Sonny Corleone",
        "Jack Sparrow",
        "Will Turner",
        "Elizabeth Swann",
        "Davy Jones",
        "Rick Grimes",
        "Daryl",
        "Michonne",
        "Negan",
        "Walter White",
        "Jesse Pinkman",
        "Saul Goodman",
        "Gustavo Fring",
        "Volver al Futuro",
        "El Padrino",
        "Scarface",
        "Freddy Krueger",
        "Jason Voorhees",
        "Michael Myers",
        "Chucky",
        "Pennywise",
        "Silvestre Stallone",
        "Arnold Schwarzenegger",
        "Rápido y Furioso",
        "Dominic Toretto",
        "Brian O'Connel (Rápidos y furiosos)",
        "Scary Movie",
        "Ethan Hunt (Misión Imposible)",
        "Jason Bourne",
        "James Bond",
        "Scream",
        "Hannibal Lecter",
        "MacGyver",
        "Houdini",
        "Baywatch",
        "El Zorro",
        "Sargento García",
        "He-Man",
        "Forrest Gump",
        "E.T.",
        "Kevin McCallister (Mi Pobre Angelito)",
        "Willy Wonka",
        "Maximus Meridio",
        "William Wallace",
        "Tyler Durden (El Club de la pelea)",
        "Vincent Vega (Pulp Fiction)",
        "Jules Winnfield (Pulp Fiction)",
        "Mia Wallace (Pulp Fiction)",
        "La Novia (Kill Bill)",
        "Beetlejuice",
        "Jack Skellington",
        "Sally (El extraño mundo de Jack)",
        "El extraño mundo de Jack",
        "El Grinch",
        "Terminator",
        "Sarah Connor",
        "Ellen Ripley (Alien)",
        "Alien",
        "Depredador (Alien)",
        "Rambo, Rocky Balboa",
        "Jack (Titanic)",
        "Rose (Titanic)",
        "Chandler (Friends)",
        "Joey (Friends)",
        "Rachel (Friends)",
        "Monica (Friends)",
        "Ross (Friends)",
        "Phoebe (Friends)",
        "The Office",
        "Michael Scott (The Office)",
        "Dwight (The Office)",
        "Jim (The Office)",
        "Pam (The Office)",
        "Sheldon (The Big Bang Theory)",
        "Leonard (The Big Bang Theory)",
        "Penny (The Big Bang Theory)",
        "Howard (The Big Bang Theory)",
        "Barney (How I Met Your Mother)",
        "Ted (How I Met Your Mother)",
        "Robin (How I Met Your Mother)",
        "How I Met Your Mother",
        "Seinfeld",
        "Jerry (Seinfeld)",
        "George (Seinfeld)",
        "Kramer (Seinfeld)",
        "Elaine (Seinfeld)",
        "Dr. House",
        "Darth Vader (Star Wars)",
        "Luke (Star Wars)",
        "Yoda (Star Wars)",
        "Han Solo (Star Wars)",
        "Chewbacca (Star Wars)",
        "Leia (Star Wars)",
        "R2-D2 (Star Wars)",
        "C-3PO (Star Wars)",
        "Obi-Wan (Star Wars)",
        "Anakin (Star Wars)",
        "Eleven (Stranger Things)",
        "Hopper (Stranger Things)",
        "Dustin (Stranger Things)",
        "Steve Harrington (Stranger Things)",
        "Vecna (Stranger Things)",
        "Jon Snow (Game of Thrones)",
        "Daenerys (Game of Thrones)",
        "Tyrion (Game of Thrones)",
        "Arya (Game of Thrones)",
        "Cersei (Game of Thrones)",
        "Geralt (The Witcher)",
        "Ciri (The Witcher)",
        "Yennefer (The Witcher)",
        "Homelander",
        "Billy Butcher (The Boys)",
        "Omni-Man",
        "Harry Potter",
        "Hermione Granger",
        "Ron Weasley",
        "Albus Dumbledore",
        "Severus Snape",
        "Lord Voldemort",
        "Gandalf",
        "Frodo",
        "Aragorn",
        "Legolas",
        "Gollum",
        "Sam",
        "Bilbo",
        "Thorin",
        "Smaug",
        "Pepe Argento",
        "Moni Argento",
        "Coki Argento",
        "Paola Argento",
        "Dardo Fuseneco",
        "María Elena Fuseneco",
        "Yayo Guridi",
        "Pachu Peña",
        "Pablo Granados",
        "Migue Granados",
        "Gargamel"
    ]},
    { id: "3", nombre: "Super Heroes",imagen: require("../assets/SuperHeroes.png"), items: [
        "Joker",
        "Robin",
        "Bane",
        "Superman",
        "Wonder Woman",
        "Flash",
        "Aquaman",
        "Iron Man",
        "Captain America",
        "Hulk",
        "Black Widow",
        "Spiderman",
        "Venom",
        "Wolverine",
        "Magneto",
        "Professor X",
        "El Caballero de la Noche",
        "El Hombre de Acero",
        "La Liga de la Justicia",
        "Mujer Maravilla",
        "Linterna Verde",
        "Batman Inicia",
        "El Joker",
        "Escuadrón Suicida",
        "Deadpool",
        "Logan",
        "X-Men",
        "Capitán América: El Primer Vengador",
        "Thor",
        "Guardianes de la Galaxia",
        "Avengers: Los Vengadores",
        "Doctor Strange: Hechicero Supremo",
        "Alfred (Batman)",
        "Lex Luthor",
        "Catwoman",
        "Pingüino",
        "Acertijo",
        "Dos Caras",
        "Harley Quinn",
        "Batman",
        "Green Lantern",
        "Doctor Strange",
        "Hawkeye",
        "Ant-Man",
        "Black Panther",
        "Iron Man",
        "Captain America",
        "Star-Lord",
        "Gamora",
        "Drax",
        "Rocket Raccoon",
        "Groot",
        "Vision",
        "Wanda Maximoff",
        "Thanos",
        "Loki",
        "Doctor Octopus",
        "Duende Verde",
        "Nick Fury",
        "Deadpool",
        "Logan",
        "X-Men",
        "Spider-Man: De Regreso a Casa"
    ]},
    {id: "4", nombre: "Series animadas",imagen: require("../assets/SeriesAnimadas.png"), items: [
        "Alf",
"Homer",
"Marge",
"Bart",
"Lisa",
"Maggie",
"Milhouse",
"Ned Flanders",
"Apu",
"Mr. Burns",
"Moe",
"Shrek",
"Burro",
"Fiona",
"Gato con Botas",
"Buzz Lightyear",
"Woody",
"Andy (Toy Story)",
"Sid",
"Elsa",
"Anna",
"Olaf",
"Sven",
"Simba (El Rey León)",
"Nala (El Rey León)",
"Mufasa (El Rey León)",
"Aladdín (Aladdín)",
"Jazmín (Aladdín)",
"Genio (Aladdín)",
"Jafar (Aladdín)",
"Peter Pan (Peter Pan)",
"Campanita (Peter Pan)",
"Capitán Garfio (Peter Pan)",
"Winnie the Pooh",
"Piglet (Winnie the Pooh)",
"Tigger (Winnie the Pooh)",
"Eeyore (Winnie the Pooh)",
"Pinocho (Pinocho)",
"Geppetto (Pinocho)",
"Dumbo (Dumbo)",
"Timothy (Dumbo)",
"Bambi (Bambi)",
"Hada Azul (Pinocho)",
"Aurora (La Bella Durmiente)",
"Maléfica (La Bella Durmiente)",
"Felipe (La Bella Durmiente)",
"Cenicienta (Cenicienta)",
"Hada Madrina (Cenicienta)",
"Anastasia (Cenicienta)",
"Ariel (La Sirenita)",
"Sebastián (La Sirenita)",
"Flounder (La Sirenita)",
"Ursula (La Sirenita)",
"Tarzán (Tarzán)",
"Jane (Tarzán)",
"Clayton (Tarzán)",
"Tiana (La Princesa y el Sapo)",
"Naveen (La Princesa y el Sapo)",
"Doctor Facilier (La Princesa y el Sapo)",
"Rapunzel (Enredados)",
"Flynn Rider (Enredados)",
"Maximus (Enredados)",
"Gothel (Enredados)",
"Ralph (Ralph el Demoledor)",
"El Rey León",
"Aladdín",
"La Sirenita",
"La Bella y la Bestia",
"La Bella Durmiente",
"Blanca Nieves y los Siete Enanos",
"Pinocho",
"Dumbo",
"Bambi",
"Cenicienta",
"Peter Pan",
"Winnie the Pooh",
"Vanellope (Ralph el Demoledor)",
"Miguel (Coco)",
"Héctor (Coco)",
"Mama Coco",
"Remy (Ratatouille)",
"Linguini (Ratatouille)",
"Colette (Ratatouille)",
"Anton Ego (Ratatouille)",
"Merida (Valiente)",
"Rey Fergus (Valiente)",
"Bolt (Bolt)",
"La Dama y el Vagabundo",
"Los Aristogatos",
"Robin Hood",
"Taron y el Caldero Mágico",
"El Zorro y el Sabueso",
"Oliver y su Pandilla",
"La Princesa y el Sapo",
"Enredados",
"Valiente",
"Frozen",
"Moana",
"Zootopia",
"Intensamente",
"Coco",
"Soul",
"Un Gran Dinosaurio",
"Ratatouille",
"Cars",
"Buscando a Nemo",
"Monsters Inc",
"Toy Story",
"Los Increíbles",
"Up: Una Aventura de Altura",
"Wall-E",
"Unidos",
"Elementos",
"Luca",
"Gravity Falls",
"Steven Universe",
"Hora de Aventura",
"Un Show Más",
"Clarence",
"Los Padrinos Mágicos",
"Bob Esponja",
"Patricio Estrella",
"Calamardo Tentáculos",
"Rick Sanchez",
"Morty Smith (Rick y Morty)",
"Finn el Humano",
"Jake el Perro",
"Mordecai",
"Rigby",
"Gumball Watterson",
"Darwin Watterson",
"Coraje (El perro cobarde)",
"Dexter",
"Dee Dee (Dexter)",
"Burbuja",
"Bombón",
"Bellota",
"Mojo Jojo",
"Johnny Bravo",
"Scooby-Doo",
"Shaggy (Scooby-Doo)",
"Tom (Tom y Jerry)",
"Jerry (Tom y Jerry)",
"Bugs Bunny",
"Pato Lucas",
"Porky",
"Silvestre",
"Piolín",
"Correcaminos",
"Coyote",
"Demonio de Tazmania",
"Pantera Rosa",
"Garfield",
"Snoopy",
"Charlie Brown",
"Popeye, Olivia, Brutus",
"Cartman (South Park)",
"Stan Marsh (South Park)",
"Kyle (South Park)",
"Kenny (South Park)",
"Peter Griffin (Family Guy)",
"Stewie Griffin (Family Guy)",
"Brian Griffin (Family Guy)",
"Ed, Edd y Eddy",
"Scar (El Rey León)",
"Cruella de Vil",
"Hades (Hércules)",
"Papá Pitufo",
"Hello Kitty",
"El Chavo del 8",
"Don Ramón",
"Quico",
"La Chilindrina",
"Señor Barriga",
"Profesor Jirafales",
        "Doña Florinda"
    ]},
    { id: "5", nombre: "Anime",imagen: require("../assets/Anime.png"), items: [
        "Light Yagami (Death Note)",
        "L (Death Note)",
        "Misa Amane (Death Note)",
        "Near (Death Note)",
        "Yagami Soichiro (Death Note)",
        "Tanjiro Kamado (Demon Slayer)",
        "Nezuko Kamado (Demon Slayer)",
        "Zenitsu Agatsuma (Demon Slayer)",
        "Inosuke Hashibira (Demon Slayer)",
        "Gyu Tomioka (Demon Slayer)",
        "Eren Jaeger (Attack on Titan)",
        "Mikasa Ackerman (Attack on Titan)",
        "Armin Arlert (Attack on Titan)",
        "Levi Ackerman (Attack on Titan)",
        "Erwin Smith (Attack on Titan)",
        "Naruto Uzumaki (Naruto)",
        "Hinata Hyuga (Naruto)",
        "Gaara (Naruto)",
        "Jiraiya (Naruto)",
        "Sakura Haruno (Naruto)",
        "Ichigo Kurosaki (Bleach)",
        "Luffy (One Piece)",
        "Zoro (One Piece)",
        "Nami (One Piece)",
        "Sanji (One Piece)",
        "Chopper (One Piece)",
        "Robin (One Piece)",
        "Usopp (One Piece)",
        "Brook (One Piece)",
        "Franky (One Piece)",
        "Gon (Hunter x Hunter)",
        "Killua (Hunter x Hunter)",
        "Kurapika (Hunter x Hunter)",
        "Edward Elric (Fullmetal Alchemist)",
        "Alphonse Elric (Fullmetal Alchemist)",
        "Roy Mustang (Fullmetal Alchemist)",
        "Mi Vecino Totoro",
        "El Castillo Ambulante",
        "El Viaje de Chihiro",
        "La Princesa Mononoke",
        "Goku",
        "Vegeta",
        "Piccolo",
        "Frieza",
        "Cell",
        "Majin Buu",
        "Naruto",
        "Sasuke",
        "Sakura",
        "Kakashi",
        "Jiraiya",
        "Ichigo"
    ]},
    {id: "6", nombre: "Videojuegos",imagen: require("../assets/VideoJuegos.png"), items: [
        "Hollow Knight",
        "Celeste",
        "Stardew Valley",
        "Undertale",
        "Hades",
        "GTA San Andreas",
        "GTA V",
        "The Witcher 3",
        "Red Dead Redemption 2",
        "Cyberpunk 2077",
        "Assassin's Creed",
        "Minecraft",
        "Fortnite",
        "League of Legends",
        "Counter Strike",
        "CJ",
        "Tommy Vercetti",
        "Niko Bellic",
        "Kratos",
        "Atreus",
        "Zeus",
        "Play 2",
        "PES 06",
        "Resident Evil 4",
        "Silent Hill",
        "Metal Gear Solid",
        "Final Fantasy VII",
        "Steam",
        "Epic Games",
        "Ubisoft",
        "EA Games",
        "Discord",
        "Twitch",
        "YouTube",
        "World of Warcraft",
        "Mario Bros",
        "Luigi",
        "Peach",
        "Bowser",
        "Yoshi",
        "Donkey Kong",
        "Link",
        "Zelda",
        "Pikachu",
        "Ash",
        "Charizard",
        "Mewtwo",
        "Kirby",
        "Sonic",
        "Pac-Man",
        "Master Chief",
        "Lara Croft",
        "Leon (Resident Evil)",
        "Ada (Resident Evil)",
        "Jill Valentine (Resident Evil)",
        "Chris (Resident Evil)",
        "Wesker (Resident Evil)",
        "Sub-Zero (Mortal Kombat)",
        "Scorpion (Mortal Kombat)",
        "Liu Kang (Mortal Kombat)",
        "Raiden (Mortal Kombat)",
        "Ryu (Street Fighter)",
        "Ken (Street Fighter)",
        "Chun-li (Street Fighter)",
        "Mega Man",
        "Crash Bandicoot",
        "Spyro",
        "Ezio Auditore",
        "Arthur Morgan",
        "John Marston",
        "Ciri",
        "Yennefer",
        "Geralt de Rivia",
        "Steve",
        "Creeper (Minecraft)",
        "Trevor (GTA V)",
        "Michael (GTA V)",
        "Franklin (GTA V)",
        "Big Smoke (GTA)"
    ]},
];